/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BooksRouteImport } from './routes/books'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as NewsRouteImport } from './routes/news'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as ApiNewsRouteImport } from './routes/api.news'
import { Route as ApiNewsSessionRouteImport } from './routes/api.news.session'
import { Route as ApiNewsPostIdRouteImport } from './routes/api.news_.$postId'
import { Route as ApiNewsPostIdLikeRouteImport } from './routes/api.news_.$postId.like'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksRoute = BooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNewsRoute = ApiNewsRouteImport.update({
  id: '/api/news',
  path: '/api/news',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNewsSessionRoute = ApiNewsSessionRouteImport.update({
  id: '/session',
  path: '/session',
  getParentRoute: () => ApiNewsRoute,
} as any)
const ApiNewsPostIdRoute = ApiNewsPostIdRouteImport.update({
  id: '/api/news_/$postId',
  path: '/api/news/$postId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNewsPostIdLikeRoute = ApiNewsPostIdLikeRouteImport.update({
  id: '/like',
  path: '/like',
  getParentRoute: () => ApiNewsPostIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/books': typeof BooksRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/news': typeof NewsRoute
  '/services': typeof ServicesRoute
  '/videos': typeof VideosRoute
  '/api/news': typeof ApiNewsRouteWithChildren
  '/api/news/session': typeof ApiNewsSessionRoute
  '/api/news/$postId': typeof ApiNewsPostIdRouteWithChildren
  '/api/news/$postId/like': typeof ApiNewsPostIdLikeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/books': typeof BooksRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/news': typeof NewsRoute
  '/services': typeof ServicesRoute
  '/videos': typeof VideosRoute
  '/api/news': typeof ApiNewsRouteWithChildren
  '/api/news/session': typeof ApiNewsSessionRoute
  '/api/news/$postId': typeof ApiNewsPostIdRouteWithChildren
  '/api/news/$postId/like': typeof ApiNewsPostIdLikeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/books': typeof BooksRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/news': typeof NewsRoute
  '/services': typeof ServicesRoute
  '/videos': typeof VideosRoute
  '/api/news': typeof ApiNewsRouteWithChildren
  '/api/news/session': typeof ApiNewsSessionRoute
  '/api/news_/$postId': typeof ApiNewsPostIdRouteWithChildren
  '/api/news_/$postId/like': typeof ApiNewsPostIdLikeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/books'
    | '/contact'
    | '/courses'
    | '/news'
    | '/services'
    | '/videos'
    | '/api/news'
    | '/api/news/session'
    | '/api/news/$postId'
    | '/api/news/$postId/like'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/books'
    | '/contact'
    | '/courses'
    | '/news'
    | '/services'
    | '/videos'
    | '/api/news'
    | '/api/news/session'
    | '/api/news/$postId'
    | '/api/news/$postId/like'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/books'
    | '/contact'
    | '/courses'
    | '/news'
    | '/services'
    | '/videos'
    | '/api/news'
    | '/api/news/session'
    | '/api/news_/$postId'
    | '/api/news_/$postId/like'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BooksRoute: typeof BooksRoute
  ContactRoute: typeof ContactRoute
  CoursesRoute: typeof CoursesRoute
  NewsRoute: typeof NewsRoute
  ServicesRoute: typeof ServicesRoute
  VideosRoute: typeof VideosRoute
  ApiNewsRoute: typeof ApiNewsRouteWithChildren
  ApiNewsPostIdRoute: typeof ApiNewsPostIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books': {
      id: '/books'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof BooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/news': {
      id: '/api/news'
      path: '/api/news'
      fullPath: '/api/news'
      preLoaderRoute: typeof ApiNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/news/session': {
      id: '/api/news/session'
      path: '/session'
      fullPath: '/api/news/session'
      preLoaderRoute: typeof ApiNewsSessionRouteImport
      parentRoute: typeof ApiNewsRoute
    }
    '/api/news_/$postId': {
      id: '/api/news_/$postId'
      path: '/api/news/$postId'
      fullPath: '/api/news/$postId'
      preLoaderRoute: typeof ApiNewsPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/news_/$postId/like': {
      id: '/api/news_/$postId/like'
      path: '/like'
      fullPath: '/api/news/$postId/like'
      preLoaderRoute: typeof ApiNewsPostIdLikeRouteImport
      parentRoute: typeof ApiNewsPostIdRoute
    }
  }
}

interface ApiNewsRouteChildren {
  ApiNewsSessionRoute: typeof ApiNewsSessionRoute
}

const ApiNewsRouteChildren: ApiNewsRouteChildren = {
  ApiNewsSessionRoute: ApiNewsSessionRoute,
}

const ApiNewsRouteWithChildren =
  ApiNewsRoute._addFileChildren(ApiNewsRouteChildren)

interface ApiNewsPostIdRouteChildren {
  ApiNewsPostIdLikeRoute: typeof ApiNewsPostIdLikeRoute
}

const ApiNewsPostIdRouteChildren: ApiNewsPostIdRouteChildren = {
  ApiNewsPostIdLikeRoute: ApiNewsPostIdLikeRoute,
}

const ApiNewsPostIdRouteWithChildren = ApiNewsPostIdRoute._addFileChildren(
  ApiNewsPostIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BooksRoute: BooksRoute,
  ContactRoute: ContactRoute,
  CoursesRoute: CoursesRoute,
  NewsRoute: NewsRoute,
  ServicesRoute: ServicesRoute,
  VideosRoute: VideosRoute,
  ApiNewsRoute: ApiNewsRouteWithChildren,
  ApiNewsPostIdRoute: ApiNewsPostIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
